# Generated by Django 5.0.6 on 2024-05-21 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
