# Generated by Django 5.0.6 on 2024-06-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_video_thumbnails_video_video_1080p_m3u8_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_480p_m3u8',
            new_name='video_360p_m3u8',
        ),
    ]
