# Generated by Django 5.0.6 on 2024-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_video_480p_m3u8_video_video_360p_m3u8'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='master_m3u8',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
